src/Cherry.config.js, src/Cherry.js, types/cherry.d.ts
当外层元素不存在时，是否强制把cherry编辑器输出到body上（默认输出）Fixed #103
=> feat: add force append

README.CN.md, src/Previewer.js
高度有时候会获取的不对，使用bottom属性让浏览器自动计算，保证定位准确。
=> 优化：预览框宽度调节条使用bottom决定高度。

src/core/hooks/Link.js
针对 #235 的BUG，给Link hook 的url添加了排他语法
=> fix: Link hook对url进行排他处理

src/Previewer.js
**Describe the bug**
I'm implementing a plugin that render something extra into the previewer. User may write `%%specialSyntax%%` and it turns into a `div` placeholder. An async process will load data and replace the placeholder.
However in the editor, when the previewer updates, the rendered content will be totally removed.
I noticed that CherryMarkdown take **current actual HTML as snapshot and build a virtual dom tree**, then compare it with a **virtual dom tree from temp document fragment**. Due to the async-mounting strategy, it is **impossible** to avoid removing my content 😢 
Therefore in this PR:
- fix some werid virtual-dom usage
- support `data-cm-atomic` attribute in the rendered HTML. which will ignore all children of current Node so that all async-mounted things will be …
=> Fix Virtual-DOM usage and support hiding children from virtual-dom

src/toolbars/Toolbar.js, src/toolbars/hooks/Insert.js, src/toolbars/hooks/Settings.js
#268 
模仿官方注册的一个快捷键 `Ctrl + q` 来实现显示隐藏状态栏，但并不影响其他 HOOKS，例如`Ctrl-1`
=> feat: 实现快捷键显示/隐藏toolbar #268

src/sass/themes/dark.scss
原有的默认高亮在暗黑模式下会使预览框内的文字难以阅读。
修改后：
=> fix(Previewer): 调整暗黑模式下高亮行颜色

src/Previewer.js
网页版的工具栏的子窗口被点开之后，只能通过在编辑区（Editor）部分点击页面来消除，在预览区（Previewer）点击无法消除；在纯预览模式下，工具栏的子窗口被点开之后不能通过点击页面来消除。
因此在Previewer.js中仿照Editor.js中的相关内容增加了一个onMouseDown函数,使其监听预览区的鼠标点击事件，令工具栏的子窗口在点击预览界面时也能被消除
=> 添加了一个onMouseDown函数,使得工具栏的子窗口在点击预览界面时也能被消除

test/core/CommonMark.spec.ts
修复了单元测试代码中的诸多小问题，包括：
- 修正了运行单元测试时，测试点 id 与 commonmark.spec.json 对不上的问题
- 在 test/core/CommonMark.spec.ts 中加入对 <br /> 的处理
- 在 test/core/CommonMark.spec.ts 添加了清理后的 HTML 的输出
- 在 test/core/CommonMark.spec.ts 中加入对字符串首尾的空格的处理
改正这些问题后，通过的测试点数目从 172 上升到了 194。
=> fix(Unittest): 修复了单元测试代码中的诸多小问题

src/Engine.js, src/core/hooks/CodeBlock.js, src/utils/regexp.js
在之前版本的 Cherry Markdown 中，blockquote 内部的代码块会被渲染为行内代码。比如以下 markdown 无法被正确渲染：
```markdown
> ```cpp
> int main();
> ```
```
本 commit 通过在 codeblock 的 Hook 中加入对 blockquote 中的代码块的识别，解决了这个问题。
=> fix(Engine): 修复 blockquote 里，代码块被渲染为行内代码的 bug

src/utils/export.js
https://github.com/niklasvh/html2canvas/issues/2945
上述库的bug导致了使用该库的截图导出功能出现了相同的问题。
通过在预览区预处理过程中调整所有`mjx-assistive-mml`元素的`visibility`属性以修复此问题。
=> fix(Previewer): 修复html2canvas导致的含MathJax的截图导出重影问题

src/Editor.js, src/core/hooks/Suggester.js, src/utils/autoindent.js
尝试着仿照Codemirror内部对Markdown列表换行补全的实现写了一个作用与罗马数字和汉字列表的类似的实现（但是巧妙利用了列表渲染系统的特性，实现效果可能并不是特别优美）
经简单测试不会影响换行的原有功能。
同时由于不知道增加的新函数放哪所以新开了一个文件，代码结构如有不妥麻烦reviewer提出调整意见。
=> feat(Editor): 增加对罗马数字与汉字列表的换行自动补全

.vscode/preview.yml, README.CN.md, README.md, build/dev.js
1. Add Cloud Studio cloud development env for cherry-markdown project. (https://cloudstudio.net/cde)
2. Add a preview.yaml for automation run script then after started, user can see the example on the right hand side.
3. Add a port forward for Cloud Studio env (X_IDE_IS_CLOUDSTUDIO)
=> For cherry-markdown, support Cloud Studio to run examples 

vscodePlugin/package.json, vscodePlugin/src/extension.ts, vscodePlugin/src/handler/uploadFile.ts, vscodePlugin/src/types/index.ts, vscodePlugin/src/types/upload.ts, vscodePlugin/web-resources/scripts/index.js
实现了本地上传(base64)，以及PicGo上传，目前测试均正常
自定义上传我想了下一些上传服务需要签名校验，并且响应体格式不一致，这里要再讨论
=> #434 vscode插件支持配置图床

src/Cherry.config.js, src/core/hooks/CodeBlock.js, src/sass/cherry.scss, src/sass/previewer.scss, src/toolbars/PreviewerBubble.js, src/utils/codeBlockContentHandler.js
实现CodeBlock所见即所得开发，入口是类似于CopyToClip的按钮，点击后通过实例化一个CodeMirror进入编辑模式。
=> feat: CodeBlock所见即所得支持

src/toolbars/Toolbar.js
测试的结论是api并不需要收集hooks，可以直接删掉，但也影响有限，就只改了重名覆盖方式，保留收集hooks过程
=> fix: #560 toolbar合并hooks时，重名的处理方式改为保留toolbar原有hook

src/core/hooks/Suggester.js
修复了输入联想无选项时上下键失效的问题
现在无选项时使用上下键会正常移动光标并停止联想
=> fix issue #558

src/toolbars/Toolbar.js
这个init函数看起来就是为子类部分重写初始化设置的
但collectToolbarHandler和collectShortcutKey两个函数，所以子类都应该执行
（处理快捷键时也只匹配toolbar的快捷键，不匹配子类的）
其他工具栏目前默认没有快捷键，所以未看到后者的bug，一起改掉了
=> fix: #567 toolbar子类重写init导致未执行部分初始化

src/core/hooks/Suggester.js
#583 
bug原因：
在生成候选框时是用document.querySelector('.CodeMirror-cursors .CodeMirror-cursor');来定位光标位置，但是当editor处于选中任意内容时，'.CodeMirror-cursors'就没有子元素'.CodeMirror-cursor'，因此代码无法正常showsuggesterPanel。
解决方案：
在判断没有子元素'.CodeMirror-cursor'时，通过定位选中框'.CodeMirror-selected'来定位候选框，此时便可以正常showsuggesterPanel。
=> fix: 在ctrl+a全选时不能展示SuggesterPanel，但会进入Suggester状态

src/Cherry.js
=> fix: 修复默认为editOnly时status错误的问题

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/client_feedback.yml, .github/ISSUE_TEMPLATE/documentation_feedback.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/vscode_plugin_report.yml, src/Editor.js
此处存在的问题：
`mark.find()`返回的并不一定是一个range，如果用户有自己设置bookmark，那么返回的是一个position，下面的`getRange`函数则会调用失败
报错信息类似
此处修改的思路：
既然是要判断`mark.className === 'cm-fullWidth'`来确定当前mark是否为自己创建的mark，那么应该提到最上层，先判断这个条件，避免其他人的TextMarker干扰
=> fix: 修复formatFullWidthMark函数

src/locales/en_US.js, src/locales/zh_CN.js, src/toolbars/HookCenter.js, src/toolbars/hooks/WordCount.js
顶部工具栏显示当前字符数、单词数、段落数，需要至少点击一次按钮进行统计，多次点击切换显示 #291
=> feat: 增加字数统计功能

src/core/hooks/Suggester.js
1.修复了不能覆盖默认关键字的行为,如自定义’/‘关键字对应suggestlist，会不生效
2.修复@关键字选择后丢失的问题，如@key，选择后会输出key
=> fix: 修复自定义keyword覆盖问题

vscodePlugin/tsconfig.json, vscodePlugin/web-resources/scripts/index.js
fix: ts's `HeadersInit` deletion
close #744
=> fix: image loading failed in vscode plugin

vscodePlugin/package.json, vscodePlugin/src/extension.ts
当前可以选择
`active`: 每次触发标签栏的时候触发预览，依然支持右键菜单触发。
`only-manual`: 只支持右键菜单触发。
=> feat: add configuration and right-click menu processing preview

vscodePlugin/package.json
背景: 当更新到最新的vscode扩展 `v0.0.15` 时，当我第一次打开vscode，并且使用vscode打开markdown文件的时候，无论`uage`使用哪种方式都不会激活扩展预览，仅当使用右键手动打开`Open Cherry Markdown Preview` 之后，插件预览才能激活。
---
1. 更换了`VS Code 扩展的激活事件(activationEvents)`,当遇到markdown文件即激活扩展。
2. 移除了废弃的扩展激活事件。
close #776
=> fix(vscodePlugin): first open markdown will not activate the extension

src/Cherry.js, src/Factory.js, src/locales/en_US.js, src/locales/zh_CN.js, src/sass/cherry.scss, src/sass/components/shortcut_key_config.scss, src/toolbars/MenuBase.js, src/toolbars/ShortcutKeyConfigPanel.js, src/toolbars/Toolbar.js, src/toolbars/hooks/Bold.js, src/toolbars/hooks/Code.js, src/toolbars/hooks/Formula.js, src/toolbars/hooks/Header.js, src/toolbars/hooks/Image.js, src/toolbars/hooks/Italic.js, src/toolbars/hooks/Link.js, src/toolbars/hooks/Publish.js, src/toolbars/hooks/Settings.js, src/toolbars/hooks/Size.js, src/toolbars/hooks/Strikethrough.js, src/toolbars/hooks/Underline.js, src/utils/shortcutKey.js, types/cherry.d.ts, types/editor.d.ts
点击设置按钮->点击快捷键配置即可，跟`vscode`一样，双击快捷键即可编辑
先查看对应hook的快捷键，API为：`cherry.toolbar.menus.hooks['header'].shortcutKeyMap` 把 `header` 换成你的即可
API更新快捷键：`cherry.toolbar.menus.hooks['header'].updateShortcutKeyMap(旧的快捷键, 新的快捷键)`
注：旧的快捷键可以通过上面的API来获取，但新的API一定要按照旧的快捷键来，如果你不知道规则，请先查看 [https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values](Mdn官方说明)，或者参考上面的编辑方法，观察 `localStorage` 的变化来实现
对了，如果你在一个页面需要打开多个 `cherry`，他们的快捷键配置互不影响
=> feat(ShortcutKey): 增加快捷键配置能力 Closes #571

.github/workflows/pr-merge.yml
=> feat: #836 PR合并后自动清除PR在线预览相关资源

.github/workflows/pr-test.yml
=> chore: 不需要在fork仓库的pr中运行预览功能

.github/workflows/pr-test.yml
=> fix: Ensure target directories exist

client/.npmrc, client/src/components/CherryMarkdown/cherry.config.ts, types/cherry.d.ts, types/previewer.d.ts
=> fix: 对于配置config 类型的修复

.github/workflows/pr-merge-dev-npm_preview.yml
因`@cherry-markdown`已经在npm被注册，所以修改替换为`cherry-markdown-publisher`
=> fix: rename npm-dev-test package

src/sass/themes/blue.scss
#802 
1. 调整整体色调，使视觉风格更加柔和
2. 略微增强阴影效果，提升页面层次感，优化视觉体验
before:
after:
---
暂未修改
=> style: 优化“淡雅”，“清幽”主题

vscodePlugin/package.json
* rename right-click menu name  "Preview In Cherry Markdown"
close #924
=> feat(vscodePlugin): add right click menu shortcut key `F10`

vscodePlugin/src/extension.ts, vscodePlugin/web-resources/scripts/index.js
=> feat(vscodePlugin): open web  link and open file link

vscodePlugin/web-resources/index.css
refer to: https://github.com/microsoft/vscode/issues/213045#issuecomment-2211442905
=> fix(vscodePlugin): vscode dark mode and it's default theme，black scrollbar appears

.github/workflows/build.yml
因当前repo内存在分支保护规则，在dev分支下必须每个pr都得经过`build.yml`ci 的成功运行之后才允许合并，当前的文件路径过滤，会导致不在匹配路径下的文件修改pr不能被允许合并。
=> chore(ci): remove the file path filtering rules in build ci

vscodePlugin/src/webview.ts, vscodePlugin/web-resources/scripts/index.js
在之前，会获取工作区路径+markdown中文本的相对路径进行拼接，当vscode的打开的工作区不同的时候就会导致图片加载失败。
现在获取当前活动的markdown文件路径，通过计算相对于这个markdown文件的相对路径获取最终的图片绝对路径进行加载。
=> fix(vscodePlugin): relative path img

vscodePlugin/web-resources/scripts/index.js
当前如果在插件内打开一个 `https` / `http` 的链接，会自动使用默认的浏览器打开这个地址，但是 vscode plugin webview 也会发生跳转，从而产生黑屏。
https://github.com/user-attachments/assets/045e06eb-afe6-4888-aa05-8376e7605fc5
当前，在检测到为 `https` / `http` 的 `A` 链接时，依旧使用默认浏览器打开这个地址，但是阻止 `A` 链接的默认跳转行为。
https://github.com/user-attachments/assets/c980bb53-0e7c-4ac0-a742-2080984f1dfb
=> fix(vscodePlugin): prevent the default redirect of links in vscode webview

src/toolbars/Toolbar.js
close #827
将其约束为 `normal-table-${number}*${number}`
约束示范:
=> fix(type): `insert` api's `normal-table-row*col` type constraints

.gitignore, package.json, packages/cherry-markdown/package.json, packages/client/package.json, yarn.lock
可以正常引用本地的 cherry-markdown 代码(本地构建后的产物)
refer: https://stackoverflow.com/questions/73057794/yarn-not-installing-packages-from-workspace-but-instead-tries-pulling-down-from
=> fix: monorepo `cherry-markdown` local link

.github/workflows/build-client-release.yaml, .github/workflows/release.yaml, package.json, packages/vscodePlugin/package.json
https://github.com/Tencent/cherry-markdown/pull/1040 这样设置会导致 changeset 不能正确运行，则将 vscodeplugin 移除 workspace 外构建的行为都使用 ci 来完成
=> ci(global): 使用 ci 来操作将 vscodePlugin 移除 workspace 外构建

.github/workflows/release.yaml
目前 `./packages/cherry-markdown` 目录是没有 README 说明文件的，而如果根目录和 `./packages/cherry-markdown` 目前都创建一份文件很容易导致文件内容不一样，所以当前在每次发布 npm 包时使用 ci 在发布之前将文件移动到 core 目录内随着 core 一起打包
=> ci: copy README.md file in the root dir to the core release dir

.changeset/config.json, .changeset/silly-dingos-fix.md
使用 `@cherry-markdown/changesets-changelog-github` 依赖，二次处理每一条 release 信息进行格式化。
效果如
https://github.com/cherry-markdown/changesets-changelog-github/releases/tag/%40cherry-markdown%2Fchangesets-changelog-github%400.0.1
=> ci: beautify release message

.github/workflows/deploy-gh-pages.yml
1、添加gh-pages分支用于demo预览（已完成）
2、增加脚本，部署到gh-pages（当前pr）
3、github pages预览配置由当前的main分支调整为gh-pages（后续工作）
4、删除main分支的dist文件夹（后续工作）
=> 添加GitHub Pages部署工作流

packages/vscodePlugin/package.json
此 pr https://github.com/Tencent/cherry-markdown/pull/1112 的 vscodePlugin ci 中调用了 vscodePlugin 的 script build ，但是实际并没有声明，此处进行补充。
=> fix(vscode): add build script

yarn.lock
原有 yarn.lock 被混入了其他国内代理，这样导致在某些情况下(github ci) 过程中会导致不能正确下载到依赖，现将其全部统一为 npm registry
=> chore: unified as npm registry

.changeset/dirty-geese-turn.md, .changeset/good-lemons-yawn.md, .changeset/rich-papayas-melt.md, .changeset/rotten-chefs-relate.md, .changeset/sweet-carrots-study.md, package.json, packages/cherry-markdown/CHANGELOG.md, packages/client/package.json, yarn.lock
在 changeset 发布 ci 工作流里有以下问题导致发布不正确。
1. devDependencies 添加 `@cherry-markdown/changesets-changelog-github`
2.  `.changeset` 记录版本错误，将 `major`(主版本) 修改为 `minor`(次版本)
3. packages/client/package.json 将 `"private": true,` 移除。
4. 修改` packages/cherry-markdown/CHANGLOG.md` 头部为
```
```
=> fix: release ci some code format errors

packages/cherry-markdown/src/toolbars/hooks/Size.js
=> fix(快捷键): 更新快捷键映射以使用标准键名

.changeset/fix-paste-from-word.md, packages/cherry-markdown/src/Editor.js
fix #1108 
---
我去看了下从 word 里面复制出来的完整的的 text/html 内容，发现 word 中的有效的文本内容都夹在 `` 与 `` 之间，所以以此来滤下其他的元数据
可以在[这边](https://evercoder.github.io/clipboard-inspector/)看到粘贴板中的完整数据
=> fix: #1108 优化粘贴处理逻辑以支持来自 Word 的内容

.changeset/fix-toolbar-layout.md, packages/cherry-markdown/src/Cherry.js, packages/cherry-markdown/src/Previewer.js, packages/cherry-markdown/src/sass/cherry.scss, packages/cherry-markdown/src/sass/variables/semantic.scss
fix #1063 
---
目前的工具栏高度直接由屏幕宽度自行决定，不再再受 `--toolbar-height` 控制（该变量已删除）。
而使用变量 `--height-toolbar` 来监视工具栏的高度，
```javascript
const toolbarObserver = new ResizeObserver(() => {
const toolbarHeight = this.$cherry.toolbar.options.dom.offsetHeight;
this.$cherry.wrapperDom.style.setProperty('--height-toolbar', `${toolbarHeight}px`);
});
toolbarObserver.observe(this.$cherry.toolbar.options.dom);
```
该变量仅用于工具栏下方的编辑区和预览区的高度控制
```scss
.cherry-editor,
.cherry-previewer {
max-height: calc(100% - var(--height-toolbar));
min-height: calc(100% - var(--height-toolbar));
}
```
=> fix: #1063 修复工具栏的位置错误

.changeset/rework-formula-panel-ui.md, packages/cherry-markdown/src/sass/bubble_formula.scss, packages/cherry-markdown/src/sass/cherry.scss, packages/cherry-markdown/src/toolbars/BubbleFormula.js, packages/cherry-markdown/src/toolbars/hooks/Formula.js
- refactor: 对公式面板的界面的重构
- feat: 增加“文本样式”页
- fix: 修复公式菜单位置计算，防止超出右侧边界
=> feat: 重构公式面板的 HTML，优化样式和交互体验

.changeset/feat-codemirror-placeholder.md, examples/assets/scripts/index-demo.js, packages/cherry-markdown/src/Cherry.config.js, packages/cherry-markdown/src/toolbars/FloatMenu.js
Resolve #1131 
---
原有的 placeholder 会和浮动工具栏重合，我这边对浮动工具栏进行了一些适配
当然，也可考虑在有 placeholder 的时候，首行不显示浮动工具栏
=> feat: 添加 codemirror 的 placeholder 配置支持

.changeset/feat-inline-code-color.md, packages/cherry-markdown/src/Cherry.config.js, packages/cherry-markdown/src/core/hooks/CodeBlock.js, packages/cherry-markdown/src/sass/cherry.scss
=> feat: 添加行内代码颜色指示

.changeset/major-lands-push.md, packages/cherry-markdown/src/addons/advance/cherry-table-echarts-plugin.js
由于[cherry-table-echarts-plugin.js](https://github.com/Tencent/cherry-markdown/blob/dev/packages/cherry-markdown/src/addons/advance/cherry-table-echarts-plugin.js#L586)中引入了多行的`htmlContent`，在脚注中，会将不同行属性之间的换行符转换为`<br/>`，导致本该渲染的图表以文字出现。
将`htmlContent`的内容修改为一行可以解决问题，但代码可读性降低。因此我增加`styleConfig`对象来配置样式，并将`htmlContent`改为数组的形式进行拼接，以维持可读性。
**修改前：**
**修改后：**
=> fix: 修复配图表格在脚注显示异常的问题
