Tencent/cherry-markdown

- src/Previewer.js
> fix: store onScroll function in memory to remove event

- src/core/hooks/CodeBlock.js
> fix(codeBlock):  do not handle \ for prism bash

- src/core/hooks/Image.js
> fix:  连续多个音视频无法正确解析

- src/Cherry.config.js
- src/Cherry.js
- src/Editor.js
- src/Previewer.js
- types/cherry.d.ts
- types/editor.d.ts
> feat: 预览区域跟随编辑区域光标滚动

- src/utils/regexp.js
> fix: 0xA0 need to be treated as space

- examples/api.html
- src/Cherry.js
- src/utils/recount-pos.js
> feat: api:setValue() 更新内容时支持保持光标位置

- examples/markdown/basic.md
- src/core/hooks/Image.js
- test/example.md
> Support poster in video

- README.CN.md
- README.md
fix: fix README content of engine mode.
> fix: fix README content of engine mode.

- examples/head_num.html
- src/Cherry.config.js
- src/Cherry.js
- src/core/hooks/Header.js
- types/cherry.d.ts
标题的样式：
- default       默认样式，标题前面有锚点
- autonumber    标题前面有自增序号锚点
- none          标题没有锚点
> add header anchorStyle  Fixed:#134

- src/Editor.js
> feat: 增加拖拽上传功能; Fixed:#36

- src/Editor.js
- src/sass/cherry.scss
> fix(editor): fix the compatibility issue of cjk ime

- src/core/hooks/List.js
> fix: update list type regex to avoid content lost

- README.CN.md
- README.md
> docs(readme): perf theme config

- src/utils/image.js
> feat: border support for image

- src/toolbars/hooks/Bold.js
- src/toolbars/hooks/Color.js
- src/toolbars/hooks/H1.js
- src/toolbars/hooks/H2.js
- src/toolbars/hooks/H3.js
- src/toolbars/hooks/Header.js
- src/toolbars/hooks/Italic.js
- src/toolbars/hooks/List.js
- src/toolbars/hooks/Quote.js
- src/toolbars/hooks/Size.js
- src/toolbars/hooks/Strikethrough.js
- src/toolbars/hooks/Sub.js
- src/toolbars/hooks/Sup.js
- src/utils/selection.js
> feat: 没有选中文字的时候点击工具栏会自动选中光标附近的文字或行

- examples/img.html
- examples/markdown/basic.md
- src/core/hooks/Image.js
- src/toolbars/PreviewerBubble.js
- src/utils/image.js
- src/utils/imgSizeHander.js
> feat: 增加图片样式（边框、阴影、圆角）

- package.json
- yarn.lock
> chore(*): bump mermaid@9.1.7

- client/index.html
- client/markdown/basic.md
- dist/cherry-markdown.css
- src/toolbars/Toolbar.js
- 修改了函数名 `hidAlleSubMenu() -> hideAllSubMenu()`
- 关于子菜单，如下图，点击展开以后只有通过点击左侧编辑区才能收起，不符合正常操作习惯，发现是因为 `toggleSubMenu()` 函数没有合适的收起逻辑。经过修改后，再次点击按钮即可收起子菜单。
> fix: 改正了一处typo，并且修复了子菜单关闭逻辑的bug

- src/core/hooks/Suggester.js
> fix: #395 尝试无脑修复，需要humyfred确认

- dist/cherry-markdown.css
- src/sass/cherry.scss
- src/toolbars/hooks/FullScreen.js
- src/utils/dialog.js
fix : change the `z-index` of full `screen ` and `dialog`
> refactor(fullScreen) : fallback full screen(#441)

- src/sass/previewer.scss
- src/utils/tableContentHander.js
> feat: 丰富表格所见即所得功能

- src/sass/previewer.scss
- src/toolbars/PreviewerBubble.js
- src/utils/tableContentHander.js
> feat: 预览区支持hover相关逻辑、表格支持hover添加行列

- client/src/components/cherryConfigs.tsx
- dist/cherry-markdown.css
- src/Cherry.config.js
- src/sass/cherry.scss
- src/sass/themes/violet.scss
- vscodePlugin/web-resources/scripts/index.js
Adding a new theme named “淡雅” to the Markdown editor. The “淡雅” theme, featuring violet colors, aims to bring together simplicity and elegance. With this new theme, your Markdown editor will have a fresh and unique look. Now you can enjoy using your Markdown editor with the elegant and simplistic “淡雅” theme, immersing yourself in a soothing violet color scheme. Happy writing!
> add a new theme "淡雅

- src/Cherry.config.js
- src/Cherry.js
- src/Editor.js
- src/sass/cherry.scss
- types/cherry.d.ts
- types/editor.d.ts
> feat: 支持专注模式、打字机模式

- .husky/post-checkout
- .husky/post-commit
- .husky/post-merge
- .husky/pre-push
- src/sass/bubble_formula.scss
- src/sass/cherry.scss
- src/sass/formula_utils_bubble.scss
- src/toolbars/BubbleFormula.js
- src/toolbars/PreviewerBubble.js
- src/toolbars/hooks/Formula.js
- src/utils/downloadUtil.js
- src/utils/formulaUtilsHandler.js
- src/utils/svgUtils.js
- types/syntax.d.ts
> #437 优化插入公式选择模板的功能，并增加预览区域公式导出、复制操作

- src/Editor.js
- src/sass/previewer.scss
- src/sass/themes/blue.scss
- src/sass/themes/dark.scss
- src/sass/themes/green.scss
- src/sass/themes/light.scss
- src/sass/themes/red.scss
- src/sass/themes/violet.scss
- src/toolbars/PreviewerBubble.js
- src/toolbars/hooks/Audio.js
- src/toolbars/hooks/Image.js
- src/toolbars/hooks/Video.js
- src/utils/file.js
- src/utils/imgSizeHandler.js
- src/utils/tableContentHandler.js
Fix spelling error related with 'handle'
> fix issue #550

- dist/cherry-markdown.css
- dist/cherry-markdown.js
- dist/cherry-markdown.js.map
- src/toolbars/PreviewerBubble.js
- src/utils/code-preview-language-setting.js
> fix issue #552 代码块的copy功能bug修复

- src/Cherry.js
- src/Previewer.js
- src/utils/export.js
> fix: api `export` optional parameter types

- dist/addons/cherry-code-block-mermaid-plugin.js
- dist/addons/cherry-code-block-plantuml-plugin.js
- dist/cherry-markdown.core.common.js
- dist/cherry-markdown.core.js
- dist/cherry-markdown.engine.core.common.js
- dist/cherry-markdown.engine.core.esm.js
- dist/cherry-markdown.engine.core.js
- dist/cherry-markdown.esm.js
- dist/cherry-markdown.js
- dist/cherry-markdown.js.map
- dist/cherry-markdown.min.js
- dist/fonts/ch-icon.eot
- dist/fonts/ch-icon.ttf
- dist/fonts/ch-icon.woff
- dist/fonts/ch-icon.woff2
- src/Cherry.js
- src/Engine.js
- src/toolbars/Toolbar.js
- src/toolbars/hooks/Graph.js
- src/toolbars/hooks/List.js
fix: remove `insert` and `setValue` return value
close #578
> fix:  types of external `api`, `Engine` and `toolbarHandlers` APIs,

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/client-report.yml
- .github/ISSUE_TEMPLATE/docs-report.yml
- .github/ISSUE_TEMPLATE/feature-report.yml
- .github/ISSUE_TEMPLATE/other.md
- .github/ISSUE_TEMPLATE/vscodePlugin-report.yml
- src/utils/tableContentHandler.js
> feat: 支持表格行和列拖拽改变位置所见即所得

- src/Editor.js
#595 
换成使用CodeMirror.coordsChar()方法定位，并简化部分代码。
> fix: issue#595 全角替换半角存在定位问题

- src/core/hooks/List.js
- src/utils/listContentHandler.js
- src/utils/regexp.js
Fixed #579
Closed #579
- 正则问题捕获到非list项
- list 项目并没有一个特殊的类，如果存在多个li则会出现行数不准
- 未输入修改替换优化
- 空字符串、过滤字符串取消正则优化
- 正则罗马数字
> fix:  List 预览编辑会导致格式失效

- client/src/components/CherryMarkdown/cherry.config.ts
- client/src/components/CherryMarkdown/index.vue
- client/src/components/SidePanel/index.vue
- client/src/store/storeCherry.ts
- client/src/store/storeElectronMenu.ts
- client/yarn.lock
style: rename `useMenuFile` to `storeElectronMenu`
perf: change instance 'cherry' mode
> feat(client): add `Toc` side panel

- docs/public/example/scripts/preview-demo.js
- examples/scripts/preview-demo.js
> fix: issue#594 examples 预览模式再次点击图片出现蒙层

- src/index.engine.core.js
> fix: `CherryEngine` type declaration

- README.md
- dist/cherry-markdown.js
- dist/fonts/ch-icon.eot
- dist/fonts/ch-icon.ttf
- dist/fonts/ch-icon.woff
- dist/fonts/ch-icon.woff2
- src/toolbars/Toolbar.js
因为此处不是"button"元素,手机环境下click可能是不生效的.
> Update Toolbar.js 兼容手机普通点击事件,替换为pointerup

- examples/markdown/basic.md
- src/sass/markdown.scss
> feat(kbd): add styles to \<kbd> tag & update examples

- src/core/hooks/Toc.js
> fix(Toc): use `div` replace obsolete HTML elements `dir`

- client/electron-builder.json5
- client/electron/main/index.ts
- client/electron/preload/menu/category/file.ts
- client/electron/preload/menu/index.ts
- client/src/App.vue
- client/src/components/CherryMarkdown/index.vue
chore: only retain **始终按所有用户（每台计算机）安装**
> feat(client): add file right-click menu to `*.md` and directly read file content

- docs/cherry/configuration/base.md
- docs/cherry/configuration/quick-configuration.md
- examples/head_num.html
- src/Cherry.config.js
- src/Cherry.js
- src/core/hooks/Toc.js
- src/sass/cherry.scss
- src/sass/markdown.scss
- src/toolbars/Toc.js
- types/cherry.d.ts
给目录增加自增序号，并分别通过配置控制
- 文内`[toc]`
```js
{
engine: {
syntax: {
...
toc: {
showAutoNumber: true
}
}
}
}
```
- 右侧浮动目录
```js
{
...
toolbars: {
...
showAutoNumber: true
}
}
> show auto number for toc

- .gitignore
- vscodePlugin/.vscode/extensions.json
- vscodePlugin/.vscode/launch.json
- vscodePlugin/.vscode/settings.json
- vscodePlugin/.vscode/tasks.json
- vscodePlugin/src/extension.ts
> feat(vscodePlugin): add webview icon

- .github/workflows/build.yml
- .github/workflows/pr-viewer.yml
> feat: #794 脚本支持pr预览

- .github/workflows/pr-reviewer.yml
- .github/workflows/pr-test.yml
新增了pr test 和 pr review脚本
pull_request_target 替代 pull_request解决不能访问secret的问题
> feat: 调整pr-viewer脚本

- README.JP.md
- README.md
I created Japanese translated README.
> docs: add Japanese README

- .github/workflows/pr-merge.yml
> fix: #858 修复漏洞

- examples/scripts/index-demo.js
- src/Cherry.config.js
- src/toolbars/hooks/Audio.js
- src/toolbars/hooks/File.js
- src/toolbars/hooks/Image.js
- src/toolbars/hooks/Pdf.js
- src/toolbars/hooks/Video.js
- src/toolbars/hooks/Word.js
- src/utils/file.js
- types/cherry.d.ts
- yarn.lock
支持了多文件上传，支持的文件类型有video、audio、image、word、pdf和file
在example中，我的多选配置支持如下
video: true,
audio: false,
image: true,
word: false,
pdf: true,
file: true,
> feat: #815 多文件上传

- client/src/components/CherryMarkdown/cherry.config.ts
可以参考这两个问题。
https://github.com/Tencent/cherry-markdown/issues/788
https://github.com/Tencent/cherry-markdown/issues/381#issuecomment-1455484863
> fix(client): due to proxy of the editor instance, data can't be edit

- examples/scripts/index-demo.js
- src/Cherry.config.js
- src/Cherry.js
- src/Previewer.js
- src/sass/cherry.scss
- src/toolbars/hooks/TogglePreview.js
- types/cherry.d.ts
- types/previewer.d.ts
增加「开启浮动预览窗」配置
```js
{
...
previewer: {
floatWhenClosePreviewer: true, // 开启浮动预览窗
},
...
}
```
> feat: #876 窗口浮动

- src/sass/previewer.scss
- src/utils/tableContentHandler.js
#803 
已完成：
鼠标hover到表格某一列时，在列的上方和下方出现删除按钮
当鼠标hover到删除按钮时，将将要被删除的列的边框标红
点击删除按钮删除对应列
> feat: 表格增加删除列操作

- src/toolbars/hooks/Settings.js
https://github.com/Tencent/cherry-markdown/issues/876#issuecomment-2390675553
> fix: #876 toolbar设置中的预览按钮支持窗口浮动

- .github/workflows/pr-test.yml
Ignore draft pull requests @RSS1102
> ci: Ignore draft pull requests

- .github/workflows/build.yml
- .github/workflows/pr-merge-dev-npm_preview.yml
- .github/workflows/pr-merge.yml
- .github/workflows/pr-test.yml
@sunsonliu  此pr的作用是增加触发ci的限制。
当下只有这些文件被更改时才会被触发(使用模糊匹配模式)，请帮忙确认这些文件是否为必要文件，另是否还有其他文件被更改后影响cherry-markdown包的构建预览。
> ci: some ci only after certain file directories are changed

- src/sass/cherry.scss
> feat: 顶部操作栏自适应换行

- src/Editor.js
- src/Engine.js
- src/sass/cherry.scss
- src/utils/regexp.js
> feat: #999 处理大文本缩略展示的逻辑，对单行超大文本作特殊缩略处理

- src/toolbars/hooks/InlineCode.js
> #1016 Fixed inlineCode icon issue

- .changeset/fair-bats-punch.md
- packages/client/src/components/CherryMarkdown.ts
Resolves https://github.com/Tencent/cherry-markdown/issues/1027
> chore: add `export` function,export `pdf`、`html`、`md`、`png`

- .changeset/young-socks-repeat.md
- .github/workflows/build-client-release.yaml
- .github/workflows/release.yaml
- package.json
- packages/vscodePlugin/package.json
- yarn.lock
当前目标是 main 分支，当提交代码到 main 分支，且有 changesets 可供消费，则 changeset ci 就会自动创建一个发版 pr，当 pr  合并后， ci 就会自动完成发布。
需要添加 secret:  `NPM_TOKEN` 和 `VSCE_PAT`
因 monorepo 下不能含有重复的包名称
当前将 vscodePlugin 移除 monorepo 结构中
将 vscodePlugin 恢复到之前的名称
> ci: changeset auto publish

- .changeset/afraid-ears-play.md
- packages/cherry-markdown/src/toolbars/MenuBase.js
> fix: custom menu asynchronous operation processing

- .changeset/silly-cameras-bake.md
- packages/cherry-markdown/src/Previewer.js
- packages/cherry-markdown/src/toolbars/Toolbar.js
> fix: expanded submenu moves with the parentmenu item

- .changeset/rotten-chefs-relate.md
- packages/cherry-markdown/src/core/hooks/List.js
- packages/cherry-markdown/src/sass/cherry.scss
- packages/cherry-markdown/src/sass/themes/blue.scss
- packages/cherry-markdown/src/sass/themes/dark.scss
- packages/cherry-markdown/src/sass/themes/default.scss
- packages/cherry-markdown/src/sass/themes/green.scss
- packages/cherry-markdown/src/sass/themes/light.scss
- packages/cherry-markdown/src/sass/themes/red.scss
- packages/cherry-markdown/src/sass/themes/violet.scss
> feat: support ordered list English sorting

- .changeset/good-lemons-yawn.md
- packages/cherry-markdown/src/Cherry.config.js
- packages/cherry-markdown/src/Engine.js
- packages/cherry-markdown/src/core/hooks/HtmlBlock.js
- packages/cherry-markdown/types/cherry.d.ts
> fix: #1109 增加禁用 html 的配置能力

- .changeset/late-tigers-clap.md
- .changeset/shiny-countries-jam.md
- .changeset/silly-dingos-fix.md
- .changeset/young-socks-repeat.md
- .github/workflows/pr&commit_cherry-makrdown_npm-dev.yml
- .github/workflows/pr&commit_client_dev_preview.yml
- .github/workflows/pr&commit_vscode_plugin_dev_preview.yml
- .github/workflows/release-cherry-markdown-build.yaml
- .github/workflows/release-client-build.yaml
- .github/workflows/release-vscode-plugin-build.yaml
- .github/workflows/release.yaml
- package.json
- packages/vscodePlugin/package.json
chore: @cherry-markdown/vscode-plugin rename cherry-markdown-vscode-plugin
> chore: vscode plugin preview build

- .github/workflows/release-vscode-plugin-build.yaml
- .github/workflows/release.yaml
- packages/vscodePlugin/package.json
> chore: 更新发布工作流，添加 VSCode 插件构建步骤和继承密钥

- .changeset/proud-humans-sin.md
- .github/workflows/pr&commit_vscode_plugin_dev_preview.yml
> ci(vscodePlugin): declare dev preview, dynamic dev independent version

- .changeset/clever-hounds-attend.md
- packages/cherry-markdown/src/Previewer.js
- packages/cherry-markdown/src/toolbars/PreviewerBubble.js
- packages/cherry-markdown/src/utils/imgSizeHandler.js
> fix: browser size changes picture control layer offset problem

- .changeset/clever-hounds-attend.md
Related https://github.com/Tencent/cherry-markdown/pull/1072
> chore: 修正版本声明

- .changeset/fuzzy-avocados-poke.md
- packages/cherry-markdown/src/Engine.js
> fix: 修复 node 环境下执行 engine.makeHtml()报错的问题

- .github/workflows/github-pages.yml
- .github/workflows/pr&merge_cherry-makrdown_npm-dev.yml
- .github/workflows/pr&merge_client_dev_preview.yml
- .github/workflows/pr&merge_vscode_plugin_dev_preview.yml
- .github/workflows/pr&preview-pkg.yml
- .github/workflows/release-cherry-markdown-build.yaml
- .github/workflows/release-client-build.yaml
- .github/workflows/release-vscode-plugin-build.yaml
- .github/workflows/test.yml
chore: 将 Node.js 版本更新为 lts，并在多个工作流中添加 yarn 缓存
> ci: add pkg preview

- .github/workflows/pr&merge_cherry-makrdown_npm-dev.yml
> chore: 优化 dev 包预览发布说明

- examples/assets/scripts/index-demo.js
> docs: 把demo的公式引擎改回mathjax

- .changeset/feat-new-theme-abyss.md
- packages/cherry-markdown/src/Cherry.config.js
- packages/cherry-markdown/src/sass/cherry.scss
- packages/cherry-markdown/src/sass/markdown_pure.scss
- packages/cherry-markdown/src/sass/themes/abyss.scss
- packages/cherry-markdown/src/sass/themes/dark.scss
- packages/cherry-markdown/src/sass/variables/semantic.scss
- packages/client/src/components/CherryMarkdown.ts
在 #1314 中的第二步：新的深色主题————深海 Abyss
> feat: 添加深海主题及相关样式支持

- .changeset/fix-highlight-line.md
- packages/cherry-markdown/src/Previewer.js
- packages/cherry-markdown/src/sass/previewer.scss
- packages/cherry-markdown/src/sass/themes/abyss.scss
- packages/cherry-markdown/src/sass/themes/blue.scss
- packages/cherry-markdown/src/sass/themes/dark.scss
- packages/cherry-markdown/src/sass/themes/green.scss
- packages/cherry-markdown/src/sass/themes/red.scss
- packages/cherry-markdown/src/sass/variables/semantic.scss
- packages/cherry-markdown/src/utils/imgSizeHandler.js
- packages/cherry-markdown/src/utils/imgToolHandler.js
fix #1373 
修复编辑行的高光闪烁问题，顺便美化和整理了编辑行的高光样式
> fix: #1373 修复编辑行的高光闪烁问题

- README.CN.md
- README.md
> [!NOTE]
> **What does the PR do?**
> - **README.md**: Translate some Chinese in Document and Demos into English
> - **README.md**: Make Documents and Demos express better (capital initials)
> - **README.CN.md**: Fixed the index error in README.CN.md going to other language versions
> docs: make two README files better

- packages/cherry-markdown/src/Cherry.js
- packages/cherry-markdown/src/toolbars/ShortcutKeyConfigPanel.js
- packages/cherry-markdown/src/toolbars/Toolbar.js
- packages/cherry-markdown/src/utils/image.js
- packages/cherry-markdown/src/utils/mathjax.js
- packages/cherry-markdown/src/utils/shortcutKey.js
> feat: 恢复默认快捷键时自动清空本地快捷键缓存

- README.CN.md
- README.JP.md
- README.md
> docs: add contributors bubble
